development:
  adapter: mysql2
  encoding: utf8
  database: zimobi_development
  username: root
  password: tttzzz

test: &test
  adapter: mysql2
  encoding: utf8
  database: zimobi_test
  username: root
  password: tttzzz
